@echo off
REM *********************************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Active-HDL Simulator
REM Description : Script for compiling design source files, automatically generated by Aldec Tcl Store app 1.35
REM Created on  : Wed Apr 24 04:03:09 -0700 2024
REM
REM usage: compile.bat
REM
REM *********************************************************************************************
set bin_path=C:\Aldec\Active-HDL-Student-Edition\bin
call "%bin_path%/VSimSA" -l "compile.log" -do "do -tcl tb_C7mod_compile.do"
exit %errorlevel%
