#############################################################################################
#
# File name : tb_C7mod_compile.do
# Created on: Wed Apr 24 04:03:09 -0700 2024
#
# Script automatically generated by Aldec Tcl Store app 1.35 for 'behavioral' simulation,
# in Vivado v2023.2 (64-bit) for Active-HDL simulator.
#
#############################################################################################
transcript off
onbreak {quit}
onerror {quit}

transcript on
vlib work

vlib activehdl/xpm
vlib activehdl/xil_defaultlib



vlog -sv2k12 -incr -l xpm -l xil_defaultlib -work xpm  "+incdir+../../../../roadtest.ip_user_files/ipstatic" \
	"C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \

vcom -93 -incr -work xpm  \
	"C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -93 -incr -work xil_defaultlib  \
	"../../../../roadtest.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.vhdl" \
	"../../../../roadtest.srcs/sources_1/MCU.vhd" \
	"../../../../roadtest.srcs/sources_1/TOP.vhd" \
	"../../../../roadtest.srcs/sources_1/contador_a_n.vhd" \
	"../../../../roadtest.srcs/sources_1/demux_1a4.vhd" \
	"../../../../roadtest.srcs/sources_1/mux_4a1.vhd" \
	"../../../../roadtest.srcs/sources_1/mux_4a1_n.vhd" \
	"../../../../roadtest.srcs/sources_1/one_shot.vhd" \
	"../../../../roadtest.srcs/sources_1/uart_MCU.vhd" \
	"../../../../roadtest.srcs/sources_1/uart_MCU_12MHz .vhd" \
	"../../../../roadtest.srcs/sources_1/uart_MCU_24MHz .vhd" \
	"../../../../roadtest.srcs/sources_1/uart_MCU_6MHz.vhd" \
	"../../../../roadtest.srcs/sim_1/new/tb_top.vhd" \


# compile glbl module
vlog -work xil_defaultlib "C:/vivado_proyects/roadtest/roadtest.sim/sim_1/behav/activehdl/glbl.v"

quit
